//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "elastic_index_info_tbl")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub index_name: String,
    pub reg_dt: DateTime,
    pub chg_dt: DateTime,
    pub reg_id: String,
    pub chg_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
