//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "store")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub seq: i32,
    pub name: String,
    pub r#type: String,
    pub use_yn: Option<String>,
    pub reg_id: String,
    pub chg_id: Option<String>,
    pub reg_dt: DateTimeUtc,
    pub chg_dt: Option<DateTimeUtc>,
    pub tel: Option<String>,
    pub url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
