//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subway_info_tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub seq: i32,
    pub subway_line: String,
    pub station_name: String,
    pub station_eng_name: String,
    #[sea_orm(column_type = "Decimal(Some((20, 16)))")]
    pub lat: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 16)))")]
    pub lng: Decimal,
    pub station_load_addr: String,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
