//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_no: i32,
    pub login_channel: Option<String>,
    pub token_id: Option<i64>,
    pub refresh_token: Option<String>,
    pub reg_id: Option<String>,
    pub chg_id: Option<String>,
    pub reg_dt: Option<DateTimeUtc>,
    pub chg_dt: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
