//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_phone_number_tbl")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_no: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub phone_number: String,
    pub telecom_name: String,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub chg_id: Option<String>,
    pub reg_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
