//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_location_detail_tbl")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_no: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub addr_type: String,
    pub addr: String,
    #[sea_orm(column_type = "Decimal(Some((10, 7)))")]
    pub lng: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 7)))")]
    pub lat: Decimal,
    pub reg_dt: DateTime,
    pub reg_id: String,
    pub chg_dt: Option<DateTime>,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
