//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_no: i32,
    pub user_id: String,
    pub user_pw: String,
    pub user_pw_salt: String,
    pub user_nm: String,
    pub user_birth: String,
    pub user_gender: Option<String>,
    pub main_oauth_channel: Option<String>,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub chg_id: Option<String>,
    pub reg_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
